name: agar
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0
  - python=3.12
  - spacy=3.8 # python -m spacy download en_core_web_sm
  - pip:
      - Flask==3.1.0
      - Werkzeug==3.1.0
      - black==25.1.0
      - openpyxl==3.1.0
      - pandas==2.2.0
      - pyarrow==19.0.0
      - ruff==0.11.9
