name: agar
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=25.0
  - python=3.12
  - spacy=3.8 # python -m spacy download en_core_web_sm
  - pip:
      - black==25.1
      - flask==3.1
      - openpyxl==3.1
      - pandas==2.2
      - pyarrow==19.0
      - werkzeug==3.1
